const photoNames=['Zimmer 1','Zimmer 2','Zimmer 3','Zimmer 4','Zimmer 5','WC','Keller 1','Keller 2','Keller 3','Bad','Küche','Sonstiges','Außen 1','Außen 2','Außen 3','Außen 4','Garage','Heizung','Stromzähler','Treppe'];
const renovationNames=[['roof','Dach'],['facade','Außenfassade'],['heating','Heizung'],['bathrooms','Bäder'],['electrics','Elektrik'],['pipes','Leitungen']];
const defaults={id:'',title:'Neue Objektaufnahme',address:'',buildingType:'Einfamilienhaus',yearBuilt:'',livingArea:0,length:0,width:0,floors:0,generalNotes:'',otherRenovated:false,otherRenovationText:'',photos:{},renovations:{}};
let records=[],current=null,step=0;const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function openDB(){return new Promise((resolve,reject)=>{const q=indexedDB.open('object-capture',1);q.onupgradeneeded=()=>q.result.createObjectStore('records',{keyPath:'id'});q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error)})}
async function loadRecords(){const db=await openDB();records=await new Promise((resolve,reject)=>{const q=db.transaction('records').objectStore('records').getAll();q.onsuccess=()=>resolve(q.result.sort((a,b)=>(b.updatedAt||'').localeCompare(a.updatedAt||'')));q.onerror=()=>reject(q.error)});renderList()}
async function putRecord(r){const db=await openDB();await new Promise((resolve,reject)=>{const q=db.transaction('records','readwrite').objectStore('records').put(r);q.onsuccess=resolve;q.onerror=()=>reject(q.error)})}
async function removeRecord(id){const db=await openDB();await new Promise((resolve,reject)=>{const q=db.transaction('records','readwrite').objectStore('records').delete(id);q.onsuccess=resolve;q.onerror=()=>reject(q.error)})}
function renderList(){const box=$('#records');box.innerHTML='';$('#empty').hidden=records.length>0;records.forEach(r=>{const count=Object.values(r.photos||{}).filter(p=>p.image).length,el=document.createElement('article');el.className='record';el.innerHTML=`<div class="record-main"><h3>${esc(r.title)}</h3><p>${esc(r.address||r.buildingType)}</p><p class="value">${count} von ${photoNames.length} Fotos · ${bgf(r).toLocaleString('de-DE',{maximumFractionDigits:2})} m² BGF</p></div><div class="record-actions"><button class="export">PDF / OneDrive</button><button class="delete">Löschen</button></div>`;el.querySelector('.record-main').onclick=()=>openEditor(r);el.querySelector('.export').onclick=()=>exportPDF(r);el.querySelector('.delete').onclick=async()=>{if(confirm('Aufnahme wirklich löschen?')){await removeRecord(r.id);await loadRecords()}};box.append(el)})}
function makeDynamicFields(){const photos=$('#photoGrid');photos.innerHTML='';photoNames.forEach((name,i)=>{const el=document.createElement('article');el.className='photo-card';el.dataset.photo=i;el.innerHTML=`<div class="photo-preview"><span>📷</span><img hidden alt="${esc(name)}"></div><div class="photo-content"><h3>${esc(name)}</h3><label class="photo-button">Foto aufnehmen<input type="file" accept="image/*" capture="environment" data-image="${i}"></label><label>Notiz<textarea rows="2" data-photo-note="${i}" placeholder="Notiz zu diesem Bild …"></textarea></label></div>`;photos.append(el)});const mods=$('#modernizations');mods.innerHTML='';renovationNames.forEach(([key,name])=>{const question=name==='Bäder'||name==='Leitungen'?`Wurden die ${name} erneuert?`:`Wurde die ${name} erneuert?`,el=document.createElement('div');el.className='renovation';el.innerHTML=`<h3>${question}</h3><div class="grid"><label>Jahr<input type="number" inputmode="numeric" min="1700" max="2100" data-reno-year="${key}" placeholder="Jahreszahl"></label><label>Notiz<input data-reno-note="${key}" placeholder="Optional"></label></div>`;mods.append(el)});$$('[data-image]').forEach(x=>x.onchange=e=>handlePhoto(e.target));$$('[data-photo-note]').forEach(x=>x.oninput=e=>{const p=current.photos[e.target.dataset.photo]||{};p.note=e.target.value;current.photos[e.target.dataset.photo]=p})}
async function handlePhoto(input){const file=input.files[0];if(!file)return;const image=await compress(file),key=input.dataset.image;current.photos[key]={...(current.photos[key]||{}),image};showPhoto(key);updateProgress()}
function compress(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const max=1400,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.78))};img.onerror=reject;img.src=reader.result};reader.onerror=reject;reader.readAsDataURL(file)})}
function showPhoto(key){const card=$(`[data-photo="${key}"]`),img=card.querySelector('img'),placeholder=card.querySelector('.photo-preview span'),has=current.photos[key]?.image;img.hidden=!has;placeholder.hidden=!!has;card.classList.toggle('complete',!!has);if(has)img.src=current.photos[key].image;else img.removeAttribute('src');card.querySelector('textarea').value=current.photos[key]?.note||'';card.querySelector('input[type=file]').value=''}
function updateProgress(){const n=Object.values(current.photos||{}).filter(p=>p.image).length;$('#photoProgress').textContent=`${n} von ${photoNames.length} Fotos`}
function openEditor(r){current=structuredClone({...defaults,...r,photos:r.photos||{},renovations:r.renovations||{}});for(const [k,v] of Object.entries(current)){const f=$(`[name="${k}"]`);if(f){f.type==='checkbox'?f.checked=!!v:f.value=v}}photoNames.forEach((_,i)=>showPhoto(String(i)));renovationNames.forEach(([key])=>{const x=current.renovations[key]||{};$(`[data-reno-year="${key}"]`).value=x.year||'';$(`[data-reno-note="${key}"]`).value=x.note||''});toggleOther();updateProgress();step=0;showStep();$('#listView').hidden=true;$('#editor').hidden=false;scrollTo(0,0)}
function readForm(){if(!current)return;const data=new FormData($('#form'));for(const [k,v] of data.entries())current[k]=v;['livingArea','length','width','floors'].forEach(k=>current[k]=Number($(`[name="${k}"]`).value)||0);current.otherRenovated=$('[name="otherRenovated"]').checked;renovationNames.forEach(([key])=>current.renovations[key]={year:$(`[data-reno-year="${key}"]`).value,note:$(`[data-reno-note="${key}"]`).value})}
function bgf(r){return(+r.length||0)*(+r.width||0)*(+r.floors||0)}
function updateBGF(){if(current)readForm();$('#bgf').textContent=`${bgf(current||defaults).toLocaleString('de-DE',{maximumFractionDigits:2})} m²`}
function showStep(){readForm();$$('.page').forEach((p,i)=>p.hidden=i!==step);$$('#steps button').forEach((b,i)=>b.classList.toggle('active',i===step));if(step===2)renderSummary();scrollTo(0,0)}
function renderSummary(){const count=Object.values(current.photos||{}).filter(p=>p.image).length,mods=renovationNames.map(([key,name])=>{const x=current.renovations[key]||{};return `<div class="summary-row"><span>${name}</span><b>${esc(x.year||'Keine Angabe')}</b>${x.note?`<small>${esc(x.note)}</small>`:''}</div>`}).join('');const thumbs=photoNames.map((name,i)=>{const p=current.photos[i]||{};return `<div class="thumb">${p.image?`<img src="${p.image}" alt="${esc(name)}">`:'<span>Kein Foto</span>'}<b>${esc(name)}</b>${p.note?`<small>${esc(p.note)}</small>`:''}</div>`}).join('');$('#summary').innerHTML=`<div class="summary-hero"><small>OBJEKTAUFNAHME</small><strong>${esc(current.title)}</strong><span>${count} von ${photoNames.length} Fotos</span></div><div class="card"><h2>Gebäudedaten</h2><div class="summary-row"><span>Adresse</span><b>${esc(current.address||'Keine Angabe')}</b></div><div class="summary-row"><span>Gebäudetyp</span><b>${esc(current.buildingType)}</b></div><div class="summary-row"><span>Baujahr</span><b>${esc(current.yearBuilt||'Keine Angabe')}</b></div><div class="summary-row"><span>Wohnfläche</span><b>${current.livingArea||0} m²</b></div><div class="summary-row"><span>Abmessungen</span><b>${current.length||0} × ${current.width||0} m · ${current.floors||0} Stockwerke</b></div><div class="summary-row"><span>Brutto-Grundfläche</span><b>${bgf(current).toLocaleString('de-DE',{maximumFractionDigits:2})} m²</b></div></div><div class="card"><h2>Modernisierungen</h2>${mods}${current.otherRenovated?`<div class="summary-row"><span>Sonstiges</span><b>${esc(current.otherRenovationText||'Ja')}</b></div>`:''}</div><h2 class="section-title">Fotodokumentation</h2><div class="thumb-grid">${thumbs}</div>${current.generalNotes?`<div class="card"><h2>Sonstige Angaben</h2><p>${esc(current.generalNotes).replace(/\n/g,'<br>')}</p></div>`:''}`}
function pdfText(doc,text,x,y,width){const lines=doc.splitTextToSize(String(text||'Keine Angabe'),width);doc.text(lines,x,y);return y+lines.length*5.2}
function pdfHeader(doc,title){doc.setFillColor(22,63,60);doc.rect(0,0,210,22,'F');doc.setTextColor(255,255,255);doc.setFontSize(14);doc.setFont('helvetica','bold');doc.text(title,15,14);doc.setTextColor(21,35,33)}
function pdfFooter(doc,page){doc.setFontSize(8);doc.setTextColor(104,118,116);doc.text(`Objektaufnahme · Seite ${page}`,15,290)}
async function exportPDF(r){try{const {jsPDF}=window.jspdf,doc=new jsPDF({unit:'mm',format:'a4',compress:true});let page=1,y=40;pdfHeader(doc,'Objektaufnahme');doc.setFontSize(24);doc.setFont('helvetica','bold');y=pdfText(doc,r.title,15,y,180);doc.setFontSize(11);doc.setFont('helvetica','normal');y=pdfText(doc,r.address,15,y+8,180)+16;const fields=[['Gebäudetyp',r.buildingType],['Baujahr',r.yearBuilt],['Wohnfläche',`${r.livingArea||0} m²`],['Gebäudeabmessungen',`${r.length||0} × ${r.width||0} m`],['Stockwerke',r.floors||0],['Brutto-Grundfläche',`${bgf(r).toLocaleString('de-DE',{maximumFractionDigits:2})} m²`]];fields.forEach(([label,value])=>{doc.setFont('helvetica','bold');doc.text(label,15,y);doc.setFont('helvetica','normal');doc.text(String(value||'Keine Angabe'),75,y);y+=9});y+=5;doc.setFont('helvetica','bold');doc.setFontSize(15);doc.text('Modernisierungen',15,y);y+=9;doc.setFontSize(10);renovationNames.forEach(([key,name])=>{const v=r.renovations?.[key]||{};doc.setFont('helvetica','bold');doc.text(`${name}:`,15,y);doc.setFont('helvetica','normal');y=pdfText(doc,[v.year||'Keine Angabe',v.note].filter(Boolean).join(' · '),55,y,140)+3});if(r.otherRenovated){doc.setFont('helvetica','bold');doc.text('Sonstiges:',15,y);doc.setFont('helvetica','normal');y=pdfText(doc,r.otherRenovationText||'Ja',55,y,140)+3}if(r.generalNotes){y+=5;doc.setFont('helvetica','bold');doc.setFontSize(15);doc.text('Sonstige Angaben',15,y);doc.setFont('helvetica','normal');doc.setFontSize(10);pdfText(doc,r.generalNotes,15,y+8,180)}pdfFooter(doc,page);for(let i=0;i<photoNames.length;i++){const p=r.photos?.[i];if(!p?.image)continue;doc.addPage();page++;pdfHeader(doc,photoNames[i]);let imageY=31,imageW=180,imageH=190;try{const props=doc.getImageProperties(p.image),ratio=props.width/props.height;imageH=Math.min(200,imageW/ratio);if(imageH===200)imageW=imageH*ratio;doc.addImage(p.image,'JPEG',(210-imageW)/2,imageY,imageW,imageH,undefined,'FAST');imageY+=imageH+9}catch{doc.setFontSize(10);doc.text('Das Foto konnte nicht eingefügt werden.',15,imageY);imageY+=12}doc.setFontSize(11);doc.setFont('helvetica','bold');doc.text('Notiz',15,imageY);doc.setFont('helvetica','normal');pdfText(doc,p.note||'Keine Notiz',15,imageY+7,180);pdfFooter(doc,page)}const safe=(r.title||'Objektaufnahme').replace(/[^a-zA-Z0-9äöüÄÖÜß_-]+/g,'_'),fileName=`${safe}_${new Date().toISOString().slice(0,10)}.pdf`,blob=doc.output('blob'),file=new File([blob],fileName,{type:'application/pdf'});if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({title:r.title,text:'In OneDrive unter StartUP/3_Vertriebsabteilung/Wertermittlung/Objekte speichern.',files:[file]})}else doc.save(fileName)}catch(error){if(error?.name!=='AbortError'){console.error(error);alert('Das PDF konnte nicht erstellt werden.')}}}
function toggleOther(){$('#otherRenovationNote').hidden=!$('[name="otherRenovated"]').checked}
function closeEditor(){current=null;$('#editor').hidden=true;$('#listView').hidden=false;loadRecords();scrollTo(0,0)}
makeDynamicFields();$$('.create').concat([$('#new')]).forEach(b=>b.onclick=()=>openEditor({...defaults,id:crypto.randomUUID(),photos:{},renovations:{}}));$$('#steps button').forEach((b,i)=>b.onclick=()=>{step=i;showStep()});$('#cancel').onclick=closeEditor;$('#save').onclick=async()=>{readForm();if(!current.title.trim()){alert('Bitte eine Bezeichnung eingeben.');return}current.updatedAt=new Date().toISOString();await putRecord(current);closeEditor()};$('[name="otherRenovated"]').onchange=toggleOther;$('#form').oninput=()=>{updateBGF();if(step===2)renderSummary()};loadRecords();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');
