const defaults={id:'',title:'Neue Immobilie',fileNumber:'',valuationDate:new Date().toISOString().slice(0,10),street:'',postalCode:'',city:'',plotArea:0,standardLandValue:0,landValueAdjustment:1,propertyType:'Einfamilienhaus',yearBuilt:1990,totalUsefulLife:80,grossFloorArea:0,qualityStandard:'Mittel',condition:'Normal',energyStandard:'',notes:'',nhk:0,constructionPriceIndex:1,regionalFactor:1,specialComponents:0,outdoorFacilitiesPercent:4,marketAdjustmentFactor:1,specialPropertyFeatures:0};
let records=JSON.parse(localStorage.getItem('sachwert-records')||'[]'), current=null, step=0;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n||0);
function calculate(r){const year=new Date(r.valuationDate||Date.now()).getFullYear(),age=Math.max(0,year-(+r.yearBuilt||year)),rnd=Math.max(0,(+r.totalUsefulLife||0)-age),ageFactor=+r.totalUsefulLife?Math.min(1,rnd/+r.totalUsefulLife):0,land=(+r.plotArea||0)*(+r.standardLandValue||0)*(+r.landValueAdjustment||0),cost=(+r.grossFloorArea||0)*(+r.nhk||0)*(+r.constructionPriceIndex||0)*(+r.regionalFactor||0)+(+r.specialComponents||0),building=cost*ageFactor,outdoor=building*(+r.outdoorFacilitiesPercent||0)/100,pre=land+building+outdoor,adjusted=pre*(+r.marketAdjustmentFactor||0),total=Math.max(0,adjusted+(+r.specialPropertyFeatures||0));return{age,rnd,land,cost,building,outdoor,pre,adjusted,total}}
function persist(){localStorage.setItem('sachwert-records',JSON.stringify(records))}
function renderList(){const box=$('#records');box.innerHTML='';$('#empty').hidden=records.length>0;records.forEach(r=>{const c=calculate(r),el=document.createElement('article');el.className='record';el.innerHTML=`<div><h3>${escapeHTML(r.title)}</h3><p>${escapeHTML([r.street,r.city].filter(Boolean).join(', ')||r.propertyType)}</p><p class="value">${money(c.total)}</p></div><button class="delete">Löschen</button>`;el.querySelector('div').onclick=()=>openEditor(r);el.querySelector('.delete').onclick=()=>{if(confirm('Objekt wirklich löschen?')){records=records.filter(x=>x.id!==r.id);persist();renderList()}};box.append(el)})}
function escapeHTML(s){return String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function openEditor(record){current={...defaults,...record};for(const [key,val] of Object.entries(current)){const f=$(`[name="${key}"]`);if(f)f.value=val}step=0;showStep();$('#listView').hidden=true;$('#editor').hidden=false;scrollTo(0,0)}
function readForm(){const data=new FormData($('#form'));for(const [k,v] of data.entries())current[k]=v;$$('input[type=number]').forEach(f=>current[f.name]=Number(f.value)||0)}
function showStep(){readForm();$$('.page').forEach((p,i)=>p.hidden=i!==step);$$('#steps button').forEach((b,i)=>b.classList.toggle('active',i===step));if(step===3)renderResult()}
function renderResult(){const c=calculate(current),row=(a,b)=>`<div class="result-row"><span>${a}</span><strong>${money(b)}</strong></div>`;$('#result').innerHTML=`<div class="result-hero"><small>INDIKATIVER SACHWERT</small><strong>${money(c.total)}</strong><small>Alter ${c.age} Jahre · RND ${c.rnd} Jahre</small></div><div class="result-list">${row('Bodenwert',c.land)}${row('Herstellungskosten',c.cost)}${row('Alterswertminderung',-(c.cost-c.building))}${row('Gebäudesachwert',c.building)}${row('Außenanlagen',c.outdoor)}${row('Marktanpassung',c.adjusted-c.pre)}${row('Besondere Merkmale',+current.specialPropertyFeatures||0)}</div>`}
function closeEditor(){current=null;$('#editor').hidden=true;$('#listView').hidden=false;renderList();scrollTo(0,0)}
$$('.create').concat([$('#new')]).forEach(b=>b.onclick=()=>openEditor({...defaults,id:crypto.randomUUID()}));$$('#steps button').forEach((b,i)=>b.onclick=()=>{step=i;showStep()});$('#cancel').onclick=closeEditor;$('#save').onclick=()=>{readForm();if(!current.title.trim()){alert('Bitte einen Objektnamen eingeben.');return}const i=records.findIndex(r=>r.id===current.id);current.updatedAt=new Date().toISOString();i<0?records.unshift(current):records[i]=current;persist();closeEditor()};$('#form').oninput=()=>{if(step===3){readForm();renderResult()}};renderList();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');
